find_library(LIBMOSQUITTOPP_LIBRARY
	NAMES mosquittopp
	DOC "libmosquittopp"
)
find_path(LIBMOSQUITTOPP_INCLUDE_DIR
	NAMES mosquittopp.h
	DOC "libmosquittopp"
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBMOSQUITTOPP
	DEFAULT_MSG
	LIBMOSQUITTOPP_LIBRARY
	LIBMOSQUITTOPP_INCLUDE_DIR
)

mark_as_advanced(
	LIBMOSQUITTOPP_LIBRARY
	LIBMOSQUITTOPP_INCLUDE_DIR
)

if(LIBMOSQUITTOPP_FOUND)
	set(LIBMOSQUITTOPP_LIBRARIES ${LIBMOSQUITTOPP_LIBRARY})
	set(LIBMOSQUITTOPP_INCLUDE_DIRS ${LIBMOSQUITTOPP_INCLUDE_DIR})
endif()

#message(STATUS "LIBMOSQUITTOPP_FOUND: ${LIBMOSQUITTOPP_FOUND}")
#message(STATUS "LIBMOSQUITTOPP_LIBRARY: ${LIBMOSQUITTOPP_LIBRARY}")
#message(STATUS "LIBMOSQUITTOPP_INCLUDE_DIR: ${LIBMOSQUITTOPP_INCLUDE_DIR}")
